server:
  servlet:
    context-path: /tag_server
  port: 8080
  max-http-header-size: 100000000
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://118.25.40.122:3306/db_tag?serverTimezone=UTC&useSSL=false&autoReconnect=true
    username: cx
    password: cx
    
mybatis:
  type-aliases-package: com.tag.dto
  mapper-locations: classpath:mapper/**/*.xml